version: "3.8"

services:
  postgres_db:
    image: postgres:latest
    container_name: tinyURL_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: tiny-url-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s

volumes:
  postgres_db:
  redis_data:
